version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=jianrong
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_DB=opencv
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
volumes:
  db-data:

secrets:
  db_password:
    file: db_password.txt
